### ISSUE TITLE
Input filter dimension for the first convolution layer.

### ISSUE THREAD

**Issue by wwang2** [topazape/molecular-VAE#2]
Hi! 
Thanks for this implementation!

I have a question about the conv1d layer setting in your implementation here:
https://github.com/topazape/molecular-VAE/blob/99c3ec70a452041943ad15148664bf2389831f52/models.py#L12

where you specify an input filter size = 120. However, 120 is the length of the padded SMILES strings. The one-hot encoded SMILES string has a dimension of 120 x 35, the filter input filter should be 35 instead of 120 because you are convolving along the SMILES sequence. 

This also means that you need to transpose your bached sequence data for the convolution operation to correctly operate on the sequence along the right dimension. 

Just want to confirm this detail. If I am right, I can submit a PR to correct this after benchmarking.

**Comment by wwang2** [comment]
update: i have been consistently getting lower loss after this fix.

**Comment by topazape** [comment]
Hi, @wwang2. 

Thank you for your suggestion. Yes, you are correct. I misunderstood that line, please submit a PR.

Best regards.

**Comment by wwang2** [comment]
@topazape PR submitted

**Comment by topazape** [comment]
@wwang2 
Thank you for your contribution!!

**Comment by wwang2** [comment]
no problem. That is my pleasure
